#*******************************************************************************
# Copyright (c) 2019 IBM Corporation and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v2.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v20.html
#
# Contributors:
#     IBM Corporation - initial API and implementation
#*******************************************************************************

# archive the artifacts dir to preserve appropriate script file permissions
# refer to Liberty dockerhub documentation https://hub.docker.com/_/websphere-liberty/
USER root
ADD /artifacts/artifacts.tar.gz $HOME/artifacts
RUN chown -R default $HOME/artifacts
RUN chmod g+w /config/resources
RUN if [ -z $(which unzip) ]; then apt update; apt install -y unzip; fi
USER default
