/*******************************************************************************
* Copyright (c) 2019 IBM Corporation and others.
* All rights reserved. This program and the accompanying materials
* are made available under the terms of the Eclipse Public License v2.0
* which accompanies this distribution, and is available at
* http://www.eclipse.org/legal/epl-v20.html
*
* Contributors:
*     IBM Corporation - initial API and implementation
*******************************************************************************/

export const LOCALE_SET = 'LOCALE_SET';
export const CAPABILITIES_PANEL = 'CAPABILITIES_PANEL';

export const ADD_NOTIFICATION = 'ADD_NOTIFICATION';
export const REMOVE_NOTIFICATION = 'REMOVE_NOTIFICATION';

export const SET_COMMENT_GRID_LINES = 'SET_COMMENT_GRID_LINES';
export const SET_FILTERED_LOADTESTS = 'SET_FILTERED_LOADTESTS';
export const SET_FILTERED_STATUS = 'SET_FILTERED_STATUS';

export const SET_CHART_COUNTERS = 'SET_CHART_COUNTERS';

export const FETCH_PROJECT_CAPABILITIES = 'FETCH_PROJECT_CAPABILITIES';
export const FETCH_PROJECT_CAPABILITIES_FULFILLED = 'FETCH_PROJECT_CAPABILITIES_FULFILLED';
export const FETCH_PROJECT_CAPABILITIES_REJECTED = 'FETCH_PROJECT_CAPABILITIES_REJECTED';

export const FETCH_METRIC_TYPES = 'FETCH_METRIC_TYPES';
export const FETCH_METRIC_TYPES_FULFILLED = 'FETCH_METRIC_TYPES_FULFILLED';
export const FETCH_METRIC_TYPES_REJECTED = 'FETCH_METRIC_TYPES_REJECTED';

export const FETCH_PROJECTLOAD_CONFIG = 'FETCH_PROJECTLOAD_CONFIG';
export const FETCH_PROJECTLOAD_FULFILLED = 'FETCH_PROJECTLOAD_FULFILLED';
export const FETCH_PROJECTLOAD_REJECTED = 'FETCH_PROJECTLOAD_REJECTED';
export const FETCH_PROJECTLOAD_SAVE_CONFIG = 'FETCH_PROJECTLOAD_SAVE_CONFIG';
export const FETCH_PROJECTLOAD_SAVE_FULFILLED = 'FETCH_PROJECTLOAD_SAVE_FULFILLED';
export const FETCH_PROJECTLOAD_SAVE_REJECTED = 'FETCH_PROJECTLOAD_SAVE_REJECTED';

export const FETCH_METRICS = 'FETCH_METRICS';
export const FETCH_METRICS_FULFILLED = 'FETCH_METRICS_FULFILLED';
export const FETCH_METRICS_REJECTED = 'FETCH_METRICS_REJECTED';

export const FETCH_PROJECTINFO = 'FETCH_PROJECTINFO';
export const FETCH_PROJECTINFO_REJECTED = 'FETCH_PROJECTINFO_REJECTED';
export const FETCH_PROJECTINFO_FULFILLED = 'FETCH_PROJECTINFO_FULFILLED';
