################################################################################
# Copyright (c) 2019 IBM Corporation and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v2.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v20.html
#
# Contributors:
#     IBM Corporation - initial API and implementation
################################################################################

################################################################################
# Multi stage DockerFile to build the performance UI and a Docker runtime image
################################################################################
FROM centos:8.1.1911 AS node-base

RUN yum -y install nodejs \
    && yum -y update platform-python-pip-9.0.3-16.el8.noarch  python3-libs-3.6.8-23.el8.x86_64 python3-dnf-4.2.17-6.el8.noarch python3-libcomps-0.1.11-4.el8.x86_64 python3-pip-wheel-9.0.3-16.el8.noarch \
    && yum clean all \
    && rm -rf /var/cache/yum

FROM node-base AS build-performance-ui

WORKDIR /usr/src/app/dashboard

COPY dashboard /usr/src/app/dashboard
##############################################
# Build the performance dashboard (Codewind)
##############################################

RUN npm install && npm run build

############################################################
# We now have a built ui, begin setup of a new runtime image
############################################################

FROM node-base

LABEL org.opencontainers.image.title="Codewind-Performance" org.opencontainers.image.description="Codewind Performance" \
      org.opencontainers.image.url="https://codewind.dev/" \
      org.opencontainers.image.source="https://github.com/eclipse/codewind"

WORKDIR /usr/src/app

COPY .env package*.json server.js LICENSE NOTICE.md package.json loadrunner/runload.js ./
COPY monitor /usr/src/app/monitor
COPY utils /usr/src/app/utils

RUN npm ci --only=production

# Install performance UIs by copying over the built applications
COPY --from=build-performance-ui /usr/src/app/dashboard/build /usr/src/app/dashboard/build

ARG IMAGE_BUILD_TIME
ENV IMAGE_BUILD_TIME=${IMAGE_BUILD_TIME} \
    NODE_ENV=production \
    LOG_LEVEL=info \
    PORT=9095

EXPOSE 9095
# Run as the default node user from the image rather than root.
USER 1000

CMD [ "npm", "start" ]
